var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var cors=require('cors');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var admin=require('./routes/getAllRecruiter');
var getAllEmplyee=require('./routes/getAllEmployees');
var removeRec=require('./routes/deleteRec');
var removeEmp=require('./routes/deleteEmp');
var addrec=require('./routes/addrecruiter');
var updaterec=require('./routes/updaterecruiter');
var LoginVerify=require('./routes/loginVerifyroutes');
var LoginVerifyEmp=require('./routes/loginVerifyEmpRoute');
var empDetailsById=require('./routes/empDetailsById');
var updateEmpDetails=require('./routes/updateEmpDetails');
var addEmp=require('./routes/addemp');
var addrecByImg=require('./routes/addrecByimg');
var updaterecByImg=require('./routes/updaterecByImg');
var getRecById=require('./routes/getrecById');
var getjobdetails=require('./routes/job');
var addJob=require('./routes/addJob');
var getAllApply=require('./routes/apply');
var getAllInterviewDetails=require('./routes/interview');
var addedu=require('./routes/education');
var deledu=require('./routes/deleteEducation');
var response=require('./routes/response');
var removejob=require('./routes/removeJob');
var addJob=require('./routes/addJob');
var app = express();
var mail=require('./routes/email_routes');
var removeapply=require('./routes/removeApply');
var addapply=require('./routes/addApply');
var updateapply=require('./routes/updateApply');
var getApplyByid=require('./routes/updateApply');
var updateJob=require('./routes/job');
var getjobbyid=require('./routes/jobupdatebyid');
var addInterview=require('./routes/addInterview');
var updateInterview=require('./routes/updateInterview');
var getByidForInterview=require('./routes/updateInterview');
var removeInterview=require('./routes/removeInterview');
var adminVerify=require('./routes/adminverify');
var getAllEmpAppliedJobs=require('./routes/EmpAllAppliedJobs');
var addedu=require('./routes/education');
var deledu=require('./routes/deleteEducation');
var getEducationById=require('./routes/getEducationByEducationId');
var response=require('./routes/response');
var getResponseById=require('./routes/getResponseByResponseId');
var removeSelectedResponse=require('./routes/removeSelectedResponse');
var updateEducation=require('./routes/education');
var emailService=require('./routes/email_routes');
var sendAdminpassword=require('./routes/sendAdminPassword');
var recNotification=require('./routes/recNotification');
var getRecNotification=require('./routes/getRecNotification');
var empNotification=require('./routes/empNotification');
var getEmpNotification=require('./routes/getAllEmpNotification');
var getAllDataForEmpNotification=require('./routes/getAllDataForEmpNotification');
var getApplyIdByEmpAndJob=require('./routes/getApplyForRecNotification');
var getAllRecNotification=require('./routes/getAllRecNotification');
var getResByApplyId=require('./routes/getResByApplyId');
var RecruiterPostedJob=require('./routes/RecruiterPostedJob');
var getcandidates=require('./routes/getcandidates');
var similar_job_for_emp=require('./routes/similar_job_for_emp');
var companyType=require('./routes/companyType');
var getSpecificCompany=require('./routes/getSpecificCompany');
var getEmpByid=require('./routes/getEmpByid');
var getEmpProfile=require('./routes/getEmpProfile');
var geteduid=require('./routes/getEducationByEmpid');
var changeEmpPassword=require('./routes/changeEmpPassword');
var getEmpFieldByempId=require('./routes/getEmpFieldByempId');
var getcompanyname=require('./routes/getcompanyname');
var getJobByField=require('./routes/getJobByField');
var getJobByIdForSingleJobField=require('./routes/getJobByIdForSingleJobField');
var getAppliedJobIdOfEmp=require('./routes/applied_job_Id_of_Emp');
var getAllEmpAppliedJobsForEmp=require('./routes/empAppliedJobsForEmp');
var getjobbyrecidForeEmp=require('./routes/getjobbyrecidForeEmp');
var getjobbyId=require('./routes/getjobbyid');
var getJobByRecId=require('./routes/getJobByRecId');
var relatedcandidates=require('./routes/relatedcandidates');
var jobsforemp=require('./routes/jobsforemp');
var addCv=require('./routes/addCv');
var getCv=require('./routes/getCv');
var getAllEducationByEmpId=require('./routes/getAllEducationByEmpId');
var getEmppasswordid=require('./routes/empPasswordByid');
var deletemongojob=require('./routes/deletejob');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use(cors());
app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/admin',admin);
app.use('/getAllEmployee',getAllEmplyee);
app.use('/removeRec',removeRec);
app.use('/removeEmp',removeEmp);
app.use('/addrecruiter',addrec);
app.use('/updaterecruiter',updaterec);
app.use('/loginVerify',LoginVerify);
app.use('/loginVerifyEmp',LoginVerifyEmp);
app.use('/empDetailsById',empDetailsById);
app.use('/updateEmpDetails',updateEmpDetails);
app.use('/addEmp',addEmp);
app.use('/addrecbyimg',addrecByImg);
app.use('/updaterec',updaterecByImg);
app.use('/getRecById',getRecById);
app.use('/maildemo',mail);
app.use('/showjob',getjobdetails);
app.use('/applyjob',getAllApply);
app.use('/interview',getAllInterviewDetails);
app.use('/addjob',addJob);
app.use('/updateJob',updateJob);
app.use('/addedu',addedu);
app.use('/deledu',deledu);
app.use('/response',response);
app.use('/removejob',removejob);
app.use('/addJob',addJob);
app.use('/removeapply',removeapply);
app.use('/addapply',addapply);
app.use('/updateapply',updateapply);
app.use('/getapplybyid',getApplyByid);
app.use('/getjobbyid',getjobbyid);
app.use('/addInterview',addInterview);
app.use('/updateInterview',updateInterview);
app.use('/getByIdForInterview',getByidForInterview);
app.use('/removeInterview',removeInterview);
app.use('/adminverify',adminVerify);
app.use('/empAppliedJobs',getAllEmpAppliedJobs);
app.use('/getEducationById',getEducationById);
app.use('/response',response);
app.use('/getResponseById',getResponseById);
app.use('/removeSelectedResponse',removeSelectedResponse);
app.use('/updateEducation',updateEducation);
app.use('/email',emailService);
app.use('/sendAdminPassword',sendAdminpassword);
app.use('/recNotification',recNotification);
app.use('/getAllDataForRecNotification',getRecNotification);
app.use('/empNotification',empNotification);
app.use('/getEmpNotification',getEmpNotification);
app.use('/getAllDataForEmpNotification',getAllDataForEmpNotification);
app.use('/getApplyIdByEmpAndJob',getApplyIdByEmpAndJob);
app.use('/getAllRecNotification',getAllRecNotification);
app.use('/getResByApplyId',getResByApplyId);
app.use('/RecruiterPostedJob',RecruiterPostedJob);
app.use('/getcandidates',getcandidates);
app.use('/similarJobForEmp',similar_job_for_emp);
app.use('/comapnyType',companyType);
app.use('/getSpecificCompany',getSpecificCompany);
app.use('/getEmpByid',getEmpByid);
app.use('/getEmpProfile',getEmpProfile);
app.use('/geteduid',geteduid);
app.use('/changePassword',changeEmpPassword);
app.use('/getEmpFieldByempId',getEmpFieldByempId);
app.use('/getcompanyname',getcompanyname);
app.use('/getJobByField',getJobByField);
app.use('/getJobByIdForSingleJobField',getJobByIdForSingleJobField);
app.use('/getAppliedJobIdOfEmp',getAppliedJobIdOfEmp);
app.use('/getAllEmpAppliedJobsForEmp',getAllEmpAppliedJobsForEmp);
app.use('/getjobbyrecidForeEmp',getjobbyrecidForeEmp);
app.use('/getjobbyId',getjobbyId);
app.use('/getJobByRecId',getJobByRecId);
app.use('/relatedcandidates',relatedcandidates);
app.use('/jobsforemp',jobsforemp);
app.use('/addCv',addCv);
app.use('/getCv',getCv);
app.use('/getAllEducationByEmpId',getAllEducationByEmpId);
app.use('/getEmppasswordid',getEmppasswordid);
app.use('/deletejob',deletemongojob);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
